version: '3'

services:
    brevets:
        build: brevets/.
        command: flask_brevets.py
        ports: 
          - "5001:5000"
        depends_on:
            - brevetsdb
        environment:
            MONGODB_HOSTNAME: brevetsdb
    brevetsdb:
        image: mongo:5.0.5

